[tool.pytest.ini_options]
pythonpath = ["src"]

[flake8]
# Fájlok és könyvtárak, amiket figyelmen kívül kell hagyni
exclude =
    .git,
    __pycache__,
    .venv,
    venv,
    env,
    build,
    dist,
    *.pyc,
    *.egg-info,
    *.json,
    # Példa külső modulok könyvtáraira vagy konkrét fájlokra:
    # site-packages,
    # _argcomplete.py,
    # code.py,
    # external_libs,